# -*- coding: utf-8 -*-
"""HolaMun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l75f2GMhEJIPQiAIbyt-pcEKpJEGdCKA
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit -q

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit-lottie

# Commented out IPython magic to ensure Python compatibility.
# %%writefile HolaMundo.py
# 
import streamlit as st
st.title("Hola, mundo")
st.write("Nombre: Andrea Hernández García")
st.write("Carrera: Ingenieria en sistemas computacionales")
st.write("No.control: 19091346")
st.write("Edad: 22 años")
st.write("Prueba")

!streamlit run HolaMundo.py & npx localtunnel --port 8501 & wget -q -O -ipv4icanhazip.com



